import { Download, FileSpreadsheet, MoreHorizontal } from 'lucide-react'
import type { FilePart } from '../../types/chat'

export function GeneratedFileCard({part}:{part:FilePart}) {
  const name=part.fileName||part.file_name||'Generated file'
  const format=part.fileFormat||part.file_format||name.split('.').pop()||'file'
  const url=part.downloadUrl||part.download_url
  return <div className="flex items-center gap-3 rounded-xl border border-slate-200 bg-white p-3 shadow-sm">
    <div className="flex size-10 items-center justify-center rounded-xl bg-emerald-50 text-emerald-600"><FileSpreadsheet size={19}/></div>
    <div className="min-w-0 flex-1"><p className="truncate text-xs font-bold text-slate-800">{name}</p><p className="mt-1 text-[10px] uppercase text-slate-400">Generated by AI · {format}</p></div>
    {url&&<a href={url} download className="rounded-lg p-2 text-slate-400 hover:bg-slate-100 hover:text-indigo-600" title="Download generated file"><Download size={16}/></a>}
    <button className="rounded-lg p-2 text-slate-400 hover:bg-slate-100" title="More file actions"><MoreHorizontal size={16}/></button>
  </div>
}
