import { useState } from 'react'
import { Check, Pin, X } from 'lucide-react'
import { usePinChatResultToDashboard } from '../../hooks/api/useDashboard'
import type { SourceMeta } from '../../types/chat'
import type { DashboardWidgetSource, WidgetType } from '../../types/dashboard'

export function PinToDashboardButton({conversationId,messageId,source,chartConfig}:{conversationId:string;messageId:string;source:SourceMeta;chartConfig?:Record<string,unknown>|null}){
 const [open,setOpen]=useState(false);const [title,setTitle]=useState(source.source_name);const [type,setType]=useState<WidgetType>(chartConfig?'bar_chart':'table');const pin=usePinChatResultToDashboard()
 const submit=()=>{const dashboardSource:DashboardWidgetSource={source_type:source.source_type==='tool'?'chat_result':source.source_type,source_name:source.source_name,doctype:source.doctype||(source.source_type==='doctype'?source.source_name:null),report_name:source.report_name||(source.source_type==='report'?source.source_name:null),filters:source.filters,fields:source.fields};pin.mutate({conversation_id:conversationId,message_id:messageId,title,widget_type:type,source:dashboardSource,chart_config:chartConfig||undefined},{onSuccess:()=>setOpen(false)})}
 return <>{<button onClick={()=>setOpen(true)} className="btn-secondary"><Pin size={14}/>Pin to Overview</button>}{pin.isSuccess&&<span className="ml-2 inline-flex items-center gap-1 text-xs font-semibold text-emerald-600"><Check size={13}/>Pinned to Overview</span>}{open&&<div className="fixed inset-0 z-[90] flex items-center justify-center bg-slate-950/50 p-4"><div className="w-full max-w-sm rounded-2xl bg-white shadow-2xl"><header className="flex items-center justify-between border-b p-5"><div><h2 className="font-bold text-slate-900">Pin to Overview</h2><p className="mt-1 text-xs text-slate-400">The widget will refresh from {source.source_name}.</p></div><button onClick={()=>setOpen(false)} className="rounded-lg p-2 hover:bg-slate-100"><X size={16}/></button></header><div className="space-y-4 p-5"><label className="block text-xs font-bold">Widget title<input value={title} onChange={e=>setTitle(e.target.value)} className="mt-2 h-10 w-full rounded-xl border px-3 text-sm"/></label><label className="block text-xs font-bold">Widget type<select value={type} onChange={e=>setType(e.target.value as WidgetType)} className="mt-2 h-10 w-full rounded-xl border px-3 text-sm"><option value="table">Table</option><option value="bar_chart">Bar chart</option><option value="line_chart">Line chart</option><option value="donut_chart">Donut chart</option><option value="kpi">KPI</option></select></label>{pin.isError&&<p className="text-xs text-rose-600">{pin.error instanceof Error?pin.error.message:'Unable to pin this widget.'}</p>}</div><footer className="flex justify-end gap-2 border-t p-4"><button onClick={()=>setOpen(false)} className="btn-secondary">Cancel</button><button disabled={pin.isPending||!title.trim()} onClick={submit} className="btn-primary">{pin.isPending?'Pinning…':'Pin widget'}</button></footer></div></div>}</>
}
