ANALYTICS_CATALOG = {
    "monthly_sales_trend": {"title": "Monthly Sales Trend", "source_name": "Sales Invoice", "date_field": "posting_date", "metrics": [{"field": "grand_total", "function": "sum", "label": "Sales"}], "group_by": ["month"], "default_chart": "line", "required_fields": ["posting_date", "grand_total"]},
    "top_customers_by_outstanding": {"title": "Top Customers by Outstanding", "source_name": "Sales Invoice", "metrics": [{"field": "outstanding_amount", "function": "sum", "label": "Outstanding"}], "group_by": ["customer"], "default_chart": "bar", "required_fields": ["customer", "outstanding_amount"]},
    "purchase_orders_by_supplier": {"title": "Purchase Orders by Supplier", "source_name": "Purchase Order", "metrics": [{"field": "grand_total", "function": "sum", "label": "Purchase Order Value"}], "group_by": ["supplier"], "default_chart": "bar", "required_fields": ["supplier", "grand_total"]},
    "sales_orders_by_status": {"title": "Sales Orders by Status", "source_name": "Sales Order", "metrics": [{"field": "name", "function": "count", "label": "Count"}], "group_by": ["status"], "default_chart": "pie", "required_fields": ["status", "name"]},
    "quotation_value_by_month": {"title": "Quotation Value by Month", "source_name": "Quotation", "date_field": "transaction_date", "metrics": [{"field": "grand_total", "function": "sum", "label": "Quotation Value"}], "group_by": ["month"], "default_chart": "line", "required_fields": ["transaction_date", "grand_total"]},
    "customers_by_territory": {"title": "Customers by Territory", "source_name": "Customer", "metrics": [{"field": "name", "function": "count", "label": "Customers"}], "group_by": ["territory"], "default_chart": "bar", "required_fields": ["territory", "name"]},
    "suppliers_by_country": {"title": "Suppliers by Country", "source_name": "Supplier", "metrics": [{"field": "name", "function": "count", "label": "Suppliers"}], "group_by": ["country"], "default_chart": "bar", "required_fields": ["country", "name"]},
    "items_by_item_group": {"title": "Items by Item Group", "source_name": "Item", "metrics": [{"field": "name", "function": "count", "label": "Items"}], "group_by": ["item_group"], "default_chart": "bar", "required_fields": ["item_group", "name"]},
}
