import json
from datetime import date, datetime
from io import BytesIO
from typing import Any

from openpyxl import Workbook
from openpyxl.styles import Alignment, Border, Font, PatternFill, Side
from openpyxl.utils import get_column_letter


def write_excel(title: str, rows: list[dict[str, Any]], metadata: dict | None = None) -> bytes:
    metadata = metadata or {}
    columns = list(dict.fromkeys(key for row in rows for key in row))
    workbook = Workbook()
    sheet = workbook.active
    sheet.title = "ERP Export"
    last_column = max(1, len(columns))
    sheet.merge_cells(start_row=1, start_column=1, end_row=1, end_column=last_column)
    cell = sheet.cell(1, 1, title)
    cell.font = Font(size=16, bold=True, color="FFFFFF")
    cell.fill = PatternFill("solid", fgColor="25314C")
    cell.alignment = Alignment(vertical="center")
    sheet.row_dimensions[1].height = 30

    row_number = 3
    labels = (("Source", metadata.get("source")), ("Generated By", metadata.get("generated_by")), ("Generated At", metadata.get("generated_at")), ("Filters", json.dumps(metadata.get("filters") or {}, ensure_ascii=False)))
    for label, value in labels:
        if value is not None:
            sheet.cell(row_number, 1, label).font = Font(bold=True, color="475569")
            sheet.cell(row_number, 2, str(value))
            row_number += 1

    header_row = row_number + 1
    thin = Side(style="thin", color="CBD5E1")
    for index, column in enumerate(columns, 1):
        header = sheet.cell(header_row, index, column.replace("_", " ").title())
        header.font = Font(bold=True, color="FFFFFF")
        header.fill = PatternFill("solid", fgColor="4F46E5")
        header.alignment = Alignment(horizontal="left")
        header.border = Border(bottom=thin)

    for row_index, row in enumerate(rows, header_row + 1):
        for column_index, column in enumerate(columns, 1):
            value = row.get(column)
            if isinstance(value, (dict, list, tuple)):
                value = json.dumps(value, ensure_ascii=False, default=str)
            output = sheet.cell(row_index, column_index, value)
            key = column.lower()
            if isinstance(value, (int, float)) and any(term in key for term in ("amount", "total", "value", "price", "rate")):
                output.number_format = f'"{metadata.get("currency") or "INR"}" #,##0.00'
            elif isinstance(value, (date, datetime)) or "date" in key:
                output.number_format = "dd-mmm-yyyy"

    sheet.freeze_panes = f"A{header_row + 1}"
    sheet.auto_filter.ref = f"A{header_row}:{get_column_letter(last_column)}{max(header_row, header_row + len(rows))}"
    for index, column in enumerate(columns, 1):
        values = [column.replace("_", " ").title(), *(str(row.get(column, "")) for row in rows[:200])]
        sheet.column_dimensions[get_column_letter(index)].width = min(max(len(value) for value in values) + 2, 45)

    stream = BytesIO()
    workbook.save(stream)
    return stream.getvalue()
