from __future__ import annotations


FIELD_ALIASES = {
    "Customer": {
        "name": "customer_name",
        "customer name": "customer_name",
        "customer_name": "customer_name",
        "mobile": "mobile_no",
        "phone": "mobile_no",
        "email": "email_id",
        "territory": "territory",
        "group": "customer_group",
        "customer group": "customer_group",
    },
    "Supplier": {
        "name": "supplier_name",
        "supplier name": "supplier_name",
        "supplier_name": "supplier_name",
        "mobile": "mobile_no",
        "phone": "mobile_no",
        "email": "email_id",
        "country": "country",
        "group": "supplier_group",
        "supplier group": "supplier_group",
    },
    "Item": {
        "name": "item_name",
        "item name": "item_name",
        "product": "item_name",
        "code": "item_code",
        "item code": "item_code",
        "item group": "item_group",
        "group": "item_group",
        "uom": "stock_uom",
    },
    "Sales Invoice": {
        "name": "name",
        "invoice": "name",
        "invoice no": "name",
        "invoice number": "name",
        "customer": "customer",
        "customer name": "customer",
        "date": "posting_date",
        "invoice date": "posting_date",
        "month": "posting_date",
        "amount": "grand_total",
        "value": "grand_total",
        "total": "grand_total",
        "balance": "outstanding_amount",
        "outstanding": "outstanding_amount",
        "unpaid amount": "outstanding_amount",
        "unpaid_amount": "outstanding_amount",
        "status": "status",
    },
    "Purchase Invoice": {
        "name": "name",
        "invoice": "name",
        "invoice no": "name",
        "bill no": "bill_no",
        "supplier": "supplier",
        "supplier name": "supplier",
        "date": "posting_date",
        "invoice date": "posting_date",
        "bill date": "bill_date",
        "month": "posting_date",
        "amount": "grand_total",
        "value": "grand_total",
        "total": "grand_total",
        "balance": "outstanding_amount",
        "outstanding": "outstanding_amount",
        "unpaid amount": "outstanding_amount",
        "unpaid_amount": "outstanding_amount",
        "status": "status",
    },
    "Sales Order": {
        "name": "name",
        "order": "name",
        "order no": "name",
        "customer": "customer",
        "customer name": "customer",
        "date": "transaction_date",
        "order date": "transaction_date",
        "month": "transaction_date",
        "amount": "grand_total",
        "value": "grand_total",
        "total": "grand_total",
        "status": "status",
    },
    "Purchase Order": {
        "name": "name",
        "order": "name",
        "po": "name",
        "po no": "name",
        "supplier": "supplier",
        "supplier name": "supplier",
        "date": "transaction_date",
        "order date": "transaction_date",
        "month": "transaction_date",
        "amount": "grand_total",
        "value": "grand_total",
        "total": "grand_total",
        "status": "status",
    },
    "Quotation": {
        "name": "name",
        "quotation": "name",
        "quote": "name",
        "customer": "party_name",
        "customer name": "party_name",
        "party": "party_name",
        "date": "transaction_date",
        "quotation date": "transaction_date",
        "month": "transaction_date",
        "amount": "grand_total",
        "value": "grand_total",
        "total": "grand_total",
        "status": "status",
    },
}


DEFAULT_FIELDS = {
    "Customer": ["name", "customer_name", "customer_group", "territory", "mobile_no", "email_id"],
    "Supplier": ["name", "supplier_name", "supplier_group", "country", "mobile_no", "email_id"],
    "Item": ["name", "item_code", "item_name", "item_group", "stock_uom", "disabled"],
    "Sales Invoice": ["name", "customer", "posting_date", "grand_total", "outstanding_amount", "status"],
    "Purchase Invoice": ["name", "supplier", "posting_date", "bill_no", "bill_date", "grand_total", "outstanding_amount", "status"],
    "Sales Order": ["name", "customer", "transaction_date", "delivery_date", "grand_total", "status"],
    "Purchase Order": ["name", "supplier", "transaction_date", "schedule_date", "grand_total", "status"],
    "Quotation": ["name", "quotation_to", "party_name", "transaction_date", "valid_till", "grand_total", "status"],
    "Delivery Note": ["name", "customer", "posting_date", "grand_total", "status"],
    "Purchase Receipt": ["name", "supplier", "posting_date", "grand_total", "status"],
    "Material Request": ["name", "material_request_type", "transaction_date", "schedule_date", "status"],
    "Lead": ["name", "lead_name", "company_name", "status"],
    "Opportunity": ["name", "opportunity_from", "party_name", "status", "opportunity_amount"],
    "Project": ["name", "project_name", "status", "percent_complete"],
    "Task": ["name", "subject", "status", "exp_start_date", "exp_end_date"],
    "Employee": ["name", "employee_name", "department", "designation", "status"],
    "Issue": ["name", "subject", "status", "priority", "opening_date"],
}


def map_field_alias(doctype: str, fieldname: str) -> str:
    normalized = " ".join(str(fieldname).replace("_", " ").lower().split())
    aliases = FIELD_ALIASES.get(doctype, {})
    return aliases.get(normalized) or aliases.get(str(fieldname)) or str(fieldname)


def get_default_fields(doctype: str) -> list[str]:
    return list(DEFAULT_FIELDS.get(doctype, ["name"]))
