import json
from io import BytesIO
from typing import Any

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4, landscape
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle


def write_pdf_reportlab(title: str, rows: list[dict[str, Any]], metadata: dict | None = None) -> bytes:
    metadata = metadata or {}
    rows = rows[:500]
    columns = list(dict.fromkeys(key for row in rows for key in row))
    stream = BytesIO()
    document = SimpleDocTemplate(stream, pagesize=landscape(A4), rightMargin=12 * mm, leftMargin=12 * mm, topMargin=12 * mm, bottomMargin=14 * mm, title=title)
    styles = getSampleStyleSheet()
    story = [Paragraph(title, styles["Title"]), Spacer(1, 5 * mm)]
    details = f"Source: {metadata.get('source', '-')} &nbsp;&nbsp; Currency: {metadata.get('currency', '-')} &nbsp;&nbsp; Generated by: {metadata.get('generated_by', '-')} &nbsp;&nbsp; Generated at: {metadata.get('generated_at', '-')}<br/>Filters: {json.dumps(metadata.get('filters') or {}, ensure_ascii=False)}"
    story.extend([Paragraph(details, styles["BodyText"]), Spacer(1, 5 * mm)])
    if columns:
        data = [[column.replace("_", " ").title() for column in columns]]
        data.extend([[str(row.get(column, ""))[:100] for column in columns] for row in rows])
        table = Table(data, repeatRows=1, hAlign="LEFT")
        table.setStyle(TableStyle([("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#283552")), ("TEXTCOLOR", (0, 0), (-1, 0), colors.white), ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"), ("FONTSIZE", (0, 0), (-1, -1), 7), ("GRID", (0, 0), (-1, -1), .25, colors.HexColor("#CBD5E1")), ("VALIGN", (0, 0), (-1, -1), "TOP"), ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F8FAFC")])]))
        story.append(table)
    story.extend([Spacer(1, 5 * mm), Paragraph("Generated by ADV Command Center", styles["BodyText"])])
    document.build(story)
    return stream.getvalue()


def write_pdf_weasyprint(html: str) -> bytes:
    from weasyprint import HTML

    return HTML(string=html).write_pdf()
