from typing import Any

from jinja2 import Environment, select_autoescape

TEMPLATE = """<!doctype html>
<html><head><meta charset="utf-8"><title>{{ title }}</title><style>
body{font-family:Inter,Arial,sans-serif;color:#172033;margin:36px;background:#f7f8fb} .page{max-width:1200px;margin:auto;background:#fff;border:1px solid #e5e7eb;border-radius:18px;padding:32px;box-shadow:0 8px 30px #0f172a0d} h1{margin:0 0 6px;color:#19233c}.meta{display:flex;flex-wrap:wrap;gap:10px;margin:22px 0}.pill,.card{border:1px solid #e5e7eb;border-radius:10px;padding:9px 12px;background:#f8fafc;font-size:12px}.cards{display:flex;gap:12px;margin:18px 0}.card strong{display:block;font-size:20px;color:#4f46e5}table{width:100%;border-collapse:collapse;font-size:12px}th{background:#283552;color:#fff;text-align:left;padding:10px}td{border-bottom:1px solid #e5e7eb;padding:9px;vertical-align:top}tr:nth-child(even){background:#f8fafc}.chart{max-width:100%;margin:18px 0}footer{margin-top:28px;color:#64748b;font-size:11px;text-align:center}</style></head>
<body><div class="page"><h1>{{ title }}</h1><div class="meta"><span class="pill">Source: {{ metadata.source or '-' }}</span><span class="pill">Currency: {{ metadata.currency or '-' }}</span><span class="pill">Generated by: {{ metadata.generated_by or '-' }}</span><span class="pill">Generated at: {{ metadata.generated_at or '-' }}</span><span class="pill">Filters: {{ metadata.filters or {} }}</span></div><div class="cards"><div class="card"><strong>{{ rows|length }}</strong>Exported rows</div><div class="card"><strong>{{ columns|length }}</strong>Columns</div></div>{% if chart_image_base64 %}<img class="chart" src="data:image/png;base64,{{ chart_image_base64 }}" alt="Chart">{% endif %}<table><thead><tr>{% for column in columns %}<th>{{ column|replace('_',' ')|title }}</th>{% endfor %}</tr></thead><tbody>{% for row in rows %}<tr>{% for column in columns %}<td>{{ row.get(column, '') }}</td>{% endfor %}</tr>{% endfor %}</tbody></table><footer>Generated by ADV Command Center</footer></div></body></html>"""


def render_html_report(title: str, rows: list[dict[str, Any]], metadata: dict | None = None, chart_image_base64: str | None = None) -> str:
    columns = list(dict.fromkeys(key for row in rows for key in row))
    environment = Environment(autoescape=select_autoescape(default=True))
    return environment.from_string(TEMPLATE).render(title=title, rows=rows, columns=columns, metadata=metadata or {}, chart_image_base64=chart_image_base64)
