import {useState} from 'react'
import {Forward,Reply,ReplyAll,Send,TicketCheck,UserPlus} from 'lucide-react'
import {communicationApi} from '../services/communicationApi'
import type {CommunicationThread} from '../types/communication.types'
import {MailAIActionBar} from './MailAIActionBar'
import {MailAttachmentPanel} from './MailAttachmentPanel'
import {MailLinkedDocumentPanel} from './MailLinkedDocumentPanel'
const text=(html:string)=>new DOMParser().parseFromString(html,'text/html').body.textContent||''
export function MailThreadView({thread,onRefresh,onCompose}:{thread:CommunicationThread;onRefresh:()=>void;onCompose:(initial:Record<string,string>)=>void}){const latest=thread.messages.at(-1)!;const[reply,setReply]=useState('');const[busy,setBusy]=useState(false);const doReply=async()=>{setBusy(true);try{await communicationApi.reply(latest.name,{content:reply,cc:[],bcc:[],attachments:[]});setReply('');onRefresh()}finally{setBusy(false)}};const convert=async(action:'task'|'issue'|'lead')=>{await communicationApi.convert(latest.name,action);alert(`${action} created successfully`)};return <div className="h-full overflow-y-auto p-4 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-[Manrope] text-lg font-bold text-slate-900">{latest.subject}</h2><p className="mt-1 text-xs text-slate-500">From {latest.sender} · To {latest.recipients}</p><p className="mt-1 text-[10px] text-slate-400">{new Date(latest.creation.replace(' ','T')).toLocaleString('en-IN')}</p></div><div className="flex gap-2"><button onClick={()=>document.getElementById('reply-box')?.focus()} className="btn-secondary text-xs"><Reply size={13}/>Reply</button><button onClick={()=>onCompose({to:latest.sender,subject:`Fwd: ${latest.subject}`,content:`\n\n--- Forwarded message ---\n${text(latest.content)}`})} className="btn-secondary text-xs"><Forward size={13}/>Forward</button></div></div><div className="my-5 border-y border-slate-100 py-5 text-sm leading-7 text-slate-700 whitespace-pre-wrap">{text(latest.content)}</div><MailAttachmentPanel items={latest.attachments}/><div className="mt-5"><MailLinkedDocumentPanel communicationName={latest.name} doctype={thread.reference_doctype} name={thread.reference_name} onLinked={onRefresh}/></div><div className="mt-5"><p className="mb-2 text-[10px] font-bold uppercase tracking-wider text-slate-400">AI actions</p><MailAIActionBar name={latest.name} onUseDraft={setReply}/><div className="mt-2 flex flex-wrap gap-2"><button onClick={()=>convert('task')} className="btn-secondary text-xs"><TicketCheck size={13}/>Create Task</button><button onClick={()=>convert('issue')} className="btn-secondary text-xs"><TicketCheck size={13}/>Create Issue</button><button onClick={()=>convert('lead')} className="btn-secondary text-xs"><UserPlus size={13}/>Create Lead</button></div></div><div className="mt-6 rounded-xl border bg-slate-50 p-3"><textarea id="reply-box" value={reply} onChange={e=>setReply(e.target.value)} placeholder="Write a reply…" className="min-h-28 w-full resize-y bg-transparent p-2 text-sm outline-none"/><div className="flex justify-end"><button disabled={!reply.trim()||busy} onClick={doReply} className="btn-primary text-xs"><Send size={13}/>{busy?'Queuing…':'Send Reply'}</button></div></div>{thread.messages.length>1&&<div className="mt-6"><p className="text-[10px] font-bold uppercase text-slate-400">Thread timeline · {thread.messages.length} messages</p></div>}</div>}
