import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { Bell, CalendarDays, Check, ChevronDown, LogOut, Search, ShieldCheck } from 'lucide-react'
import { MobileMenuButton } from './Sidebar'
import { useAuthStore } from '../../store/useAuthStore'
import { useAppStore } from '../../store/useAppStore'

const iso=(date:Date)=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`
function preset(label:string){const now=new Date();let from:Date;const to=now;if(label==='Last 30 days')from=new Date(now.getFullYear(),now.getMonth(),now.getDate()-29);else if(label==='This quarter')from=new Date(now.getFullYear(),Math.floor(now.getMonth()/3)*3,1);else if(label==='This year')from=new Date(now.getFullYear(),0,1);else from=new Date(now.getFullYear(),now.getMonth(),1);return{from:iso(from),to:iso(to),label}}
const displayDate=(value:string)=>new Intl.DateTimeFormat('en-IN',{day:'2-digit',month:'short',year:'2-digit'}).format(new Date(`${value}T00:00:00`))

export function TopHeader() {
  const [userOpen,setUserOpen]=useState(false);const [dateOpen,setDateOpen]=useState(false);const {user,logout}=useAuthStore();const {dateRange,setDateRange}=useAppStore();const navigate=useNavigate()
  const displayName=user?.fullName||user?.user||'ERP User';const initials=displayName.split(/\s+/).map(part=>part[0]).join('').slice(0,2).toUpperCase();const company=user?.company||'ERPNext';const companyInitials=company.split(/\s+/).map(part=>part[0]).join('').slice(0,3).toUpperCase();const signOut=async()=>{await logout();navigate('/login',{replace:true})}
  return <header className="sticky top-0 z-30 flex h-[72px] items-center gap-3 border-b border-slate-200/80 bg-white/90 px-4 backdrop-blur-xl sm:px-6 lg:px-8"><MobileMenuButton/><div className="relative hidden max-w-lg flex-1 md:block"><Search className="absolute left-3.5 top-1/2 -translate-y-1/2 text-slate-400" size={17}/><input aria-label="Global search" placeholder="Search ERP data or commands…" className="h-10 w-full rounded-xl border border-slate-200 bg-slate-50/80 pl-10 pr-4 text-sm outline-none transition placeholder:text-slate-400 focus:border-indigo-300 focus:bg-white focus:ring-4 focus:ring-indigo-50"/><span className="absolute right-3 top-1/2 -translate-y-1/2 rounded-md border bg-white px-1.5 py-0.5 text-[10px] font-semibold text-slate-400">⌘ K</span></div><div className="ml-auto flex items-center gap-1.5 sm:gap-2">
    <div title={company} className="hidden max-w-56 items-center gap-2 rounded-xl border border-slate-200 bg-white px-3 py-2 text-xs font-semibold text-slate-700 xl:flex"><span className="flex size-5 shrink-0 items-center justify-center rounded-md bg-indigo-50 text-[9px] font-bold text-indigo-600">{companyInitials}</span><span className="truncate">{company}</span></div>
    <div className="relative hidden lg:block"><button onClick={()=>setDateOpen(open=>!open)} aria-expanded={dateOpen} className="flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-3 py-2 text-xs font-semibold text-slate-600 transition hover:bg-slate-50"><CalendarDays size={15} className="text-slate-400"/>{displayDate(dateRange.from)} – {displayDate(dateRange.to)}<ChevronDown size={13} className={`text-slate-400 transition ${dateOpen?'rotate-180':''}`}/></button>{dateOpen&&<div className="absolute right-0 top-12 w-72 rounded-2xl border bg-white p-3 shadow-xl"><p className="px-2 pb-2 text-[10px] font-bold uppercase tracking-wider text-slate-400">Date range</p>{['This month','Last 30 days','This quarter','This year'].map(label=><button key={label} onClick={()=>{setDateRange(preset(label));setDateOpen(false)}} className="flex w-full items-center justify-between rounded-xl px-3 py-2 text-left text-xs font-semibold text-slate-600 hover:bg-slate-50">{label}{dateRange.label===label&&<Check size={13} className="text-indigo-600"/>}</button>)}<div className="mt-2 grid grid-cols-2 gap-2 border-t pt-3"><label className="text-[10px] font-bold text-slate-400">From<input type="date" value={dateRange.from} onChange={event=>setDateRange({...dateRange,from:event.target.value,label:'Custom'})} className="mt-1 h-9 w-full rounded-lg border px-2 text-[11px] text-slate-600"/></label><label className="text-[10px] font-bold text-slate-400">To<input type="date" min={dateRange.from} value={dateRange.to} onChange={event=>setDateRange({...dateRange,to:event.target.value,label:'Custom'})} className="mt-1 h-9 w-full rounded-lg border px-2 text-[11px] text-slate-600"/></label></div></div>}</div>
    <button aria-label="Notifications" className="relative rounded-xl p-2.5 text-slate-500 transition hover:bg-slate-100"><Bell size={19}/><span className="absolute right-2 top-2 size-2 rounded-full border-2 border-white bg-rose-500"/></button><div className="mx-1 hidden h-7 w-px bg-slate-200 sm:block"/><div className="relative"><button onClick={()=>setUserOpen(open=>!open)} aria-expanded={userOpen} className="flex items-center gap-2 rounded-xl p-1.5 text-left transition hover:bg-slate-50"><div className="flex size-8 items-center justify-center rounded-xl bg-gradient-to-br from-indigo-500 to-violet-600 text-xs font-bold text-white">{initials}</div><div className="hidden sm:block"><p className="max-w-32 truncate text-xs font-bold text-slate-800">{displayName}</p><p className="text-[10px] text-slate-400">ERPNext User</p></div><ChevronDown size={13} className={`hidden text-slate-400 transition sm:block ${userOpen?'rotate-180':''}`}/></button>{userOpen&&<div className="absolute right-0 top-12 w-56 rounded-2xl border bg-white p-2 shadow-xl"><div className="border-b px-3 py-2.5"><p className="truncate text-xs font-bold text-slate-800">{displayName}</p><p className="mt-1 flex items-center gap-1 text-[10px] text-emerald-600"><ShieldCheck size={11}/>ERPNext session active</p></div><button onClick={signOut} className="mt-1 flex w-full items-center gap-2 rounded-xl px-3 py-2.5 text-left text-xs font-bold text-rose-600 hover:bg-rose-50"><LogOut size={15}/>Sign out</button></div>}</div>
  </div></header>
}
