import { useParams } from 'react-router-dom'
import { ArrowRight, BookOpen, FileBarChart, Headphones, Plus, Sparkles } from 'lucide-react'
import { PageHeader } from '../components/common/PageHeader'
import { KpiCard } from '../components/common/KpiCard'
import { CommandInput } from '../components/chat/CommandInput'
import { StatusBadge } from '../components/common/Badges'
import { LoadingState } from '../components/common/LoadingState'
import { ErrorState } from '../components/common/ErrorState'
import { useModule } from '../hooks/api/useModules'

export function ModuleDetailPage(){const {moduleId='accounting'}=useParams();const query=useModule(moduleId);if(query.isLoading)return <LoadingState cards={4}/>;if(query.isError||!query.data)return <ErrorState retry={()=>void query.refetch()} message="This ERP module could not be loaded."/>;const {module,records:items}=query.data;const Icon=module.icon;return <>
  <PageHeader eyebrow="ERP module" title={module.name} description={module.description} actions={<button disabled={module.permissions?.canCreate===false} title={module.permissions?.canCreate===false?module.permissions.reason:undefined} className="btn-primary disabled:cursor-not-allowed disabled:opacity-50"><Plus size={16}/>Create new</button>}/>
  <div className="card mb-6 overflow-hidden bg-gradient-to-r from-slate-950 to-indigo-950 p-5 text-white sm:p-6"><div className="flex flex-col gap-5 lg:flex-row lg:items-center"><div className="flex items-center gap-4 lg:w-64"><div className="flex size-12 items-center justify-center rounded-2xl bg-white/10"><Icon size={23}/></div><div><p className="text-sm font-bold">{module.name} AI</p><p className="mt-1 text-xs text-indigo-200">Scoped ERPNext commands</p></div></div><div className="min-w-0 flex-1 text-slate-900"><CommandInput compact onSend={()=>undefined}/></div></div></div>
  <div className="grid grid-cols-2 gap-3 lg:grid-cols-4"><KpiCard label="This month" value={module.metric} icon={Icon} accent={module.color}/><KpiCard label="Open records" value="84" change="+6.8%" icon={FileBarChart} accent="blue"/><KpiCard label="Needs attention" value="12" change="-3.2%" trend="down" icon={Sparkles} accent="amber"/><KpiCard label="AI automations" value="7 active" icon={Sparkles} accent="violet"/></div>
  <div className="mt-6 grid gap-6 xl:grid-cols-3"><section className="card overflow-hidden xl:col-span-2"><div className="border-b px-5 py-4"><h3 className="text-sm font-bold">Recent records</h3><p className="mt-1 text-xs text-slate-400">Latest activity in {module.name}</p></div><div className="divide-y">{items.slice(0,5).map((x,i)=><div key={x} className="flex items-center gap-3 px-5 py-3.5 hover:bg-slate-50"><span className="flex size-8 items-center justify-center rounded-lg bg-slate-100 text-xs font-bold text-slate-500">{String(i+1).padStart(2,'0')}</span><div className="min-w-0 flex-1"><p className="text-xs font-bold text-slate-700">{x} – {module.slug.toUpperCase()}-2026-{1048-i*7}</p><p className="mt-1 text-[10px] text-slate-400">Updated {i+1} hour{i?'s':''} ago by Admin User</p></div><StatusBadge>{i===1?'In Progress':i===3?'Open':'Resolved'}</StatusBadge></div>)}</div></section>
  <div className="space-y-6"><section className="card p-5"><h3 className="text-sm font-bold">Quick actions</h3><div className="mt-4 space-y-1">{items.slice(0,4).map(x=><button key={x} className="flex w-full items-center justify-between rounded-xl px-3 py-2.5 text-left text-xs font-semibold text-slate-600 hover:bg-slate-50 hover:text-indigo-600">{x}<ArrowRight size={14}/></button>)}</div></section><section className="card p-5"><h3 className="text-sm font-bold">Learn & get help</h3><button className="mt-4 flex w-full items-center gap-3 rounded-xl bg-indigo-50 p-3 text-left"><BookOpen size={17} className="text-indigo-600"/><span><span className="block text-xs font-bold text-slate-700">{module.name} essentials</span><span className="text-[10px] text-slate-400">15 min learning path</span></span></button><button className="mt-2 flex w-full items-center gap-3 rounded-xl bg-slate-50 p-3 text-left"><Headphones size={17} className="text-slate-600"/><span><span className="block text-xs font-bold text-slate-700">Ask support</span><span className="text-[10px] text-slate-400">AI triage available</span></span></button></section></div></div>
  </>}
