import { useState, type ComponentType } from 'react'
import { Bell, Bot, Building2, CheckCircle2, ChevronRight, LockKeyhole, Moon, Palette, ShieldCheck, UserRound, type LucideProps } from 'lucide-react'
import { PageHeader } from '../components/common/PageHeader'
import { LoadingState } from '../components/common/LoadingState'
import { ErrorState } from '../components/common/ErrorState'
import { useCurrentUserContext } from '../hooks/api/useErpnext'

const sections=[['Profile',UserRound],['Company Context',Building2],['AI Preferences',Bot],['Security',LockKeyhole],['Data Privacy',ShieldCheck],['Notifications',Bell],['Theme',Palette]] as Array<[string,ComponentType<LucideProps>]>
function Toggle({value,onChange}:{value:boolean;onChange:()=>void}){return <button role="switch" aria-checked={value} onClick={onChange} className={`relative h-6 w-11 rounded-full transition ${value?'bg-indigo-600':'bg-slate-200'}`}><span className={`absolute top-1 size-4 rounded-full bg-white shadow transition ${value?'left-6':'left-1'}`}/></button>}

export function SettingsPage(){
  const [active,setActive]=useState('AI Preferences')
  const [toggles,setToggles]=useState([true,true,true,true])
  const context=useCurrentUserContext()
  const toggle=(i:number)=>setToggles(state=>state.map((value,index)=>index===i?!value:value))
  if(context.isLoading)return <LoadingState cards={4}/>
  if(context.isError||!context.data)return <ErrorState retry={()=>void context.refetch()}/>
  return <><PageHeader eyebrow="Workspace administration" title="Settings" description="Manage your identity, AI behavior, security, data controls, and workspace preferences."/><div className="grid gap-6 lg:grid-cols-[230px_1fr]"><nav className="card h-fit p-2">{sections.map(([name,Icon])=><button key={name} onClick={()=>setActive(name)} className={`flex w-full items-center gap-3 rounded-xl px-3 py-3 text-left text-xs font-bold transition ${active===name?'bg-indigo-50 text-indigo-700':'text-slate-500 hover:bg-slate-50'}`}><Icon size={16}/><span className="flex-1">{name}</span><ChevronRight size={13}/></button>)}</nav><section className="card overflow-hidden"><div className="border-b p-5 sm:p-6"><h2 className="font-[Manrope] text-lg font-bold">{active}</h2><p className="mt-1 text-xs text-slate-400">Configure {active.toLowerCase()} for your ADV workspace.</p></div>{active==='AI Preferences'?<div className="divide-y">{[['Enable AI insights','Surface proactive business findings and anomalies.'],['Require confirmation for write actions','Always review changes before ERPNext records are updated.'],['Allow dashboard suggestions','Let AI recommend useful visualizations and KPIs.'],['Allow training recommendations','Personalize learning based on your ERP activity.']].map(([title,desc],i)=><div key={title} className="flex items-center gap-4 p-5 sm:p-6"><div className="flex size-9 shrink-0 items-center justify-center rounded-xl bg-indigo-50 text-indigo-600"><Bot size={16}/></div><div className="min-w-0 flex-1"><p className="text-sm font-bold">{title}</p><p className="mt-1 text-xs text-slate-400">{desc}</p></div><Toggle value={toggles[i]} onChange={()=>toggle(i)}/></div>)}</div>:active==='Data Privacy'?<Privacy/>:active==='Profile'?<Profile fullName={context.data.fullName} email={context.data.user}/>:active==='Company Context'?<Company company={context.data.company} companies={context.data.allowedCompanies} currency={context.data.companyCurrency} timezone={context.data.timezone}/>:<Generic active={active}/>}</section></div></>
}

function Privacy(){return <div className="p-5 sm:p-6"><div className="rounded-2xl border border-emerald-100 bg-emerald-50 p-5"><ShieldCheck className="text-emerald-600"/><h3 className="mt-3 font-bold text-emerald-950">Private environment protected</h3><p className="mt-1 text-xs leading-5 text-emerald-800">Your workspace uses enterprise controls for every AI interaction.</p></div><div className="mt-5 divide-y rounded-2xl border">{['ERPNext data remains inside private environment','External model sharing disabled','Permission-aware responses enabled','Audit logging enabled'].map(item=><div key={item} className="flex items-center gap-3 p-4 text-sm font-semibold text-slate-700"><CheckCircle2 size={17} className="text-emerald-500"/>{item}</div>)}</div></div>}
function Profile({fullName,email}:{fullName:string;email:string}){return <div className="grid gap-5 p-5 sm:grid-cols-2 sm:p-6"><label className="text-xs font-bold text-slate-600">Full name<input defaultValue={fullName} className="mt-2 h-10 w-full rounded-xl border px-3 font-normal outline-none focus:border-indigo-300"/></label><label className="text-xs font-bold text-slate-600">Email<input defaultValue={email} className="mt-2 h-10 w-full rounded-xl border px-3 font-normal outline-none focus:border-indigo-300"/></label><label className="text-xs font-bold text-slate-600">Role<input defaultValue="System Manager" disabled className="mt-2 h-10 w-full rounded-xl border bg-slate-50 px-3 font-normal text-slate-500"/></label><label className="text-xs font-bold text-slate-600">Language<select className="mt-2 h-10 w-full rounded-xl border px-3 font-normal"><option>English (India)</option></select></label><button className="btn-primary w-fit">Save changes</button></div>}
function Company({company,companies,currency,timezone}:{company?:string;companies?:string[];currency?:string;timezone?:string}){const options=companies?.length?companies:[company||'ERPNext'];return <div className="p-5 sm:p-6"><div className="grid gap-5 sm:grid-cols-2"><label className="text-xs font-bold">Default company<select value={company||options[0]} onChange={()=>undefined} className="mt-2 h-10 w-full rounded-xl border px-3 font-normal">{options.map(item=><option key={item}>{item}</option>)}</select></label><label className="text-xs font-bold">Fiscal year<select className="mt-2 h-10 w-full rounded-xl border px-3 font-normal"><option>Current fiscal year</option></select></label><label className="text-xs font-bold">Currency<input value={currency||'INR'} readOnly className="mt-2 h-10 w-full rounded-xl border bg-slate-50 px-3 font-normal"/></label><label className="text-xs font-bold">ERP timezone<input value={timezone||'Asia/Kolkata'} readOnly className="mt-2 h-10 w-full rounded-xl border bg-slate-50 px-3 font-normal"/></label></div></div>}
function Generic({active}:{active:string}){return <div className="p-6"><div className="flex items-center gap-4 rounded-2xl bg-slate-50 p-5"><Moon className="text-indigo-600"/><div><p className="text-sm font-bold">{active} controls</p><p className="mt-1 text-xs text-slate-400">Workspace defaults are currently active. More controls will be available with your ERPNext connection.</p></div></div></div>}
