import { useLocation } from 'react-router-dom'
import { ArrowRight, Bot, Headphones, LifeBuoy, MessageCircle, Plus, Send, UserRound } from 'lucide-react'
import { PageHeader } from '../components/common/PageHeader'
import { StatusBadge } from '../components/common/Badges'
import { TicketCard } from '../components/support/TicketCard'
import { LoadingState } from '../components/common/LoadingState'
import { ErrorState } from '../components/common/ErrorState'
import { useSupportTickets } from '../hooks/api/useSupport'
import { useAuthStore } from '../store/useAuthStore'
const issues=['Unable to submit Sales Invoice','Stock Ledger mismatch','Payment Entry not reflecting','User permission issue','Report not loading','Email notification not sending']
export function SupportPage(){const path=useLocation().pathname;const company=useAuthStore(state=>state.user?.company)||'ERPNext';const ticketsOnly=path.endsWith('tickets');const helpOnly=path.endsWith('ai-help');const query=useSupportTickets();if(query.isLoading)return <LoadingState table/>;if(query.isError||!query.data)return <ErrorState retry={()=>void query.refetch()}/>;const tickets=query.data;return <><PageHeader eyebrow="AI-powered help desk" title={ticketsOnly?'Support Tickets':helpOnly?'AI Help':'Support Center'} description="Resolve ERPNext issues faster with AI diagnosis, permission-aware guidance, and seamless human handoff." actions={<button className="btn-primary"><Plus size={16}/>Create Ticket</button>}/>
{!ticketsOnly&&<><section className="card overflow-hidden"><div className="bg-gradient-to-r from-slate-950 to-indigo-950 p-5 text-white sm:p-7"><div className="flex items-start gap-4"><span className="flex size-11 shrink-0 items-center justify-center rounded-2xl bg-white/10"><Bot size={21}/></span><div><h2 className="font-[Manrope] text-lg font-bold">Hi Admin, what can I help fix?</h2><p className="mt-1 text-xs text-indigo-200">Describe the issue. I’ll check common causes before creating a ticket.</p></div></div><div className="mt-6 flex rounded-2xl bg-white p-2 shadow-xl"><input placeholder="Describe your ERPNext issue…" className="min-w-0 flex-1 bg-transparent px-3 text-sm text-slate-800 outline-none"/><button aria-label="Ask AI help" className="flex size-10 items-center justify-center rounded-xl bg-indigo-600"><Send size={16}/></button></div><div className="mt-3 flex items-center gap-2 text-[10px] text-indigo-200"><LifeBuoy size={12}/>Context: {company}</div></div></section><div className="mt-6"><h2 className="font-[Manrope] text-lg font-bold">Common issues</h2><div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{issues.map(x=><button key={x} className="card flex items-center gap-3 p-4 text-left transition hover:-translate-y-0.5 hover:border-indigo-200"><span className="flex size-9 items-center justify-center rounded-xl bg-slate-100 text-slate-500"><MessageCircle size={16}/></span><span className="flex-1 text-xs font-bold text-slate-700">{x}</span><ArrowRight size={14} className="text-slate-300"/></button>)}</div></div></>}
{!helpOnly&&<section className="card mt-6 overflow-hidden"><div className="flex items-center justify-between border-b p-5"><div><h2 className="font-bold">Recent tickets</h2><p className="mt-1 text-xs text-slate-400">AI triage and human support status</p></div><div className="flex items-center gap-2 text-[10px] font-bold text-emerald-600"><Headphones size={13}/>Human handoff available</div></div><div className="hidden overflow-x-auto sm:block"><table className="w-full min-w-[760px] text-left"><thead><tr className="border-b bg-slate-50">{['Ticket ID','Subject','Priority','Status','Assigned To','Created On'].map(x=><th key={x} className="px-5 py-3 text-[10px] uppercase tracking-wider text-slate-400">{x}</th>)}</tr></thead><tbody>{tickets.map(t=><tr key={t.id} className="border-b last:border-0"><td className="px-5 py-4 text-xs font-bold text-indigo-600">{t.id}</td><td className="px-5 py-4 text-xs font-semibold">{t.subject}</td><td className="px-5 py-4"><StatusBadge>{t.priority}</StatusBadge></td><td className="px-5 py-4"><StatusBadge>{t.status}</StatusBadge></td><td className="px-5 py-4 text-xs text-slate-500"><span className="flex items-center gap-2"><UserRound size={13}/>{t.assignedTo}</span></td><td className="px-5 py-4 text-xs text-slate-400">{t.created}</td></tr>)}</tbody></table></div><div className="grid gap-3 p-3 sm:hidden">{tickets.map(t=><TicketCard key={t.id} ticket={t}/>)}</div></section>}</>}
