import { useState } from 'react'
import { ArrowRight,Headphones,MessageCircle,Plus,UserRound } from 'lucide-react'
import { useLocation } from 'react-router-dom'
import { PageHeader } from '../components/common/PageHeader'
import { StatusBadge } from '../components/common/Badges'
import { TicketCard } from '../components/support/TicketCard'
import { SupportAIChat } from '../components/support/SupportAIChat'
import { TicketEscalationDialog } from '../components/support/TicketEscalationDialog'
import { LoadingState } from '../components/common/LoadingState'
import { ErrorState } from '../components/common/ErrorState'
import { useSupportTickets } from '../hooks/api/useSupport'
const issues=['Unable to submit Sales Invoice','Stock Ledger mismatch','Payment Entry not reflecting','User permission issue','Report not loading','Email notification not sending']
export function SupportPage(){const path=useLocation().pathname;const ticketsOnly=path.endsWith('tickets');const helpOnly=path.endsWith('ai-help');const query=useSupportTickets();const [escalate,setEscalate]=useState<string|null>(null);if(query.isLoading)return <LoadingState table/>;if(query.isError||!query.data)return <ErrorState retry={()=>void query.refetch()}/>;return <><PageHeader eyebrow="Private knowledge help desk" title={ticketsOnly?'Support Tickets':helpOnly?'AI Help':'Support Center'} description="Cited answers from approved internal knowledge, with permission-aware human escalation." actions={<button className="btn-primary" onClick={()=>setEscalate('Describe your support request')}><Plus size={16}/>Create Ticket</button>}/>{!ticketsOnly&&<><SupportAIChat onEscalate={setEscalate}/><div className="mt-6"><h2 className="font-bold">Common issues</h2><div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{issues.map(issue=><button key={issue} className="card flex items-center gap-3 p-4 text-left" onClick={()=>setEscalate(issue)}><MessageCircle size={16}/><span className="flex-1 text-xs font-bold">{issue}</span><ArrowRight size={14}/></button>)}</div></div></>}{!helpOnly&&<section className="card mt-6 overflow-hidden"><div className="flex items-center justify-between border-b p-5"><h2 className="font-bold">Recent tickets</h2><span className="flex items-center gap-2 text-[10px] font-bold text-emerald-600"><Headphones size={13}/>Human handoff available</span></div><div className="hidden overflow-x-auto sm:block"><table className="w-full min-w-[760px] text-left"><thead><tr className="border-b bg-slate-50">{['Ticket ID','Subject','Priority','Status','Assigned To','Created On'].map(x=><th key={x} className="px-5 py-3 text-[10px] uppercase text-slate-400">{x}</th>)}</tr></thead><tbody>{query.data.map(t=><tr key={t.id} className="border-b"><td className="px-5 py-4 text-xs font-bold text-indigo-600">{t.id}</td><td className="px-5 py-4 text-xs font-semibold">{t.subject}</td><td className="px-5 py-4"><StatusBadge>{t.priority}</StatusBadge></td><td className="px-5 py-4"><StatusBadge>{t.status}</StatusBadge></td><td className="px-5 py-4 text-xs text-slate-500"><span className="flex gap-2"><UserRound size={13}/>{t.assignedTo}</span></td><td className="px-5 py-4 text-xs text-slate-400">{t.created}</td></tr>)}</tbody></table></div><div className="grid gap-3 p-3 sm:hidden">{query.data.map(t=><TicketCard key={t.id} ticket={t}/>)}</div></section>}{escalate&&<TicketEscalationDialog question={escalate} onClose={()=>setEscalate(null)}/>}</>}
