import { Award, BookCheck, Flame, Medal, Star, Target, Trophy, Users } from 'lucide-react'
import { useLocation } from 'react-router-dom'
import { PageHeader } from '../components/common/PageHeader'
import { KpiCard } from '../components/common/KpiCard'
import { TrainingCourseCard } from '../components/training/TrainingCourseCard'
import { LoadingState } from '../components/common/LoadingState'
import { ErrorState } from '../components/common/ErrorState'
import { useTrainingCourses } from '../hooks/api/useTraining'
export function TrainingPage(){const path=useLocation().pathname;const leader=path.endsWith('leaderboard');const assessment=path.endsWith('assessments');const query=useTrainingCourses();if(query.isLoading)return <LoadingState/>;if(query.isError||!query.data)return <ErrorState retry={()=>void query.refetch()}/>;const courses=query.data;return <><PageHeader eyebrow="Learning academy" title={leader?'Leaderboard':assessment?'Assessments':'Training & Growth'} description="Build practical ERPNext expertise with adaptive learning paths, assessments, and team gamification."/><div className="grid grid-cols-2 gap-3 lg:grid-cols-5"><KpiCard label="Learning points" value="2,480" icon={Star} accent="amber"/><KpiCard label="Badges earned" value="12" icon={Award} accent="violet"/><KpiCard label="Company rank" value="#7" icon={Trophy} accent="indigo"/><KpiCard label="Learning streak" value="14 days" icon={Flame} accent="rose"/><KpiCard label="Completion" value="68%" icon={Target} accent="emerald"/></div>
{leader?<Leaderboard/>:assessment?<Assessments/>:<><div className="mt-8 flex items-end justify-between"><div><h2 className="font-[Manrope] text-lg font-bold">Assigned learning</h2><p className="mt-1 text-xs text-slate-400">Your personalized ERPNext learning path</p></div><button className="text-xs font-bold text-indigo-600">View all courses</button></div><div className="mt-4 grid gap-4 sm:grid-cols-2 xl:grid-cols-3 2xl:grid-cols-5">{courses.map(c=><TrainingCourseCard key={c.title} course={c}/>)}</div></>}</>}
function Leaderboard(){return <section className="card mt-6 overflow-hidden"><div className="border-b p-5"><h2 className="font-bold">Company leaderboard</h2><p className="mt-1 text-xs text-slate-400">July learning points</p></div>{['Priya Shah','Rahul Mehta','Sneha Rao','Arjun Verma','Kavya Nair','Dev Patel','Admin User'].map((x,i)=><div key={x} className={`flex items-center px-5 py-4 ${x==='Admin User'?'bg-indigo-50':''}`}><span className="w-10 font-bold text-slate-400">#{i+1}</span><span className="flex size-8 items-center justify-center rounded-full bg-slate-100 text-xs font-bold">{x.split(' ').map(y=>y[0]).join('')}</span><b className="ml-3 flex-1 text-sm">{x}</b><span className="text-xs font-bold text-indigo-600">{3480-i*165} pts</span></div>)}</section>}
function Assessments(){return <div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{['Selling Process Assessment','Stock Controls Certification','Accounts Receivable Quiz'].map((x,i)=><div className="card p-5" key={x}><Medal className="text-indigo-600"/><h3 className="mt-4 font-bold">{x}</h3><p className="mt-2 text-xs text-slate-400">{20+i*5} questions · {30+i*5} minutes</p><div className="mt-5 flex items-center justify-between"><b className="text-sm">{i===1?'Due in 3 days':i===2?'Score: 88%':'Score: 94%'}</b><button className="btn-secondary">{i===1?'Begin':'Review'}</button></div></div>)}</div>}
