import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { AlertTriangle, RefreshCw, Settings2, Trash2 } from 'lucide-react'
import type { DashboardWidgetData } from '../../types/dashboard'
import { PermissionBadge } from '../common/Badges'
import { useAuthStore } from '../../store/useAuthStore'
import { formatCurrency } from '../../utils/formatters'
import { chartPalette } from '../../theme/colors'

export function DashboardWidget({widget,onRefresh,onDelete,onEdit,busy=false}:{widget:DashboardWidgetData;onRefresh?:()=>void;onDelete?:()=>void;onEdit?:()=>void;busy?:boolean}){
 const currency=useAuthStore(state=>state.user?.companyCurrency)||'INR'
 const source=widget.source.doctype||widget.source.report_name||widget.source.source_name||'Configured source'
 return <section className="card min-w-0 overflow-hidden"><header className="flex items-start gap-3 border-b border-slate-100 px-4 py-3"><div className="min-w-0 flex-1"><h3 className="truncate text-sm font-bold text-slate-900">{widget.title}</h3><div className="mt-1 flex flex-wrap items-center gap-2"><span className="text-[10px] font-semibold uppercase tracking-wide text-slate-400">{widget.source.source_type}: {source}</span><PermissionBadge allowed={widget.permission?.allowed!==false}/></div></div><div className="flex items-center gap-1">{onRefresh&&<button onClick={onRefresh} disabled={busy} title="Refresh widget" className="rounded-lg p-2 text-slate-400 hover:bg-slate-100 hover:text-indigo-600 disabled:opacity-40"><RefreshCw size={14} className={busy?'animate-spin':''}/></button>}{onEdit&&<button onClick={onEdit} title="Configure widget" className="rounded-lg p-2 text-slate-400 hover:bg-slate-100"><Settings2 size={14}/></button>}{onDelete&&<button onClick={onDelete} title="Delete widget" className="rounded-lg p-2 text-slate-400 hover:bg-rose-50 hover:text-rose-600"><Trash2 size={14}/></button>}</div></header><div className="p-4">{widget.error?<div className="flex gap-2 rounded-xl bg-amber-50 p-4 text-xs text-amber-800"><AlertTriangle size={15}/>{widget.error}</div>:<WidgetBody widget={widget} currency={currency}/>}<p className="mt-3 text-[10px] text-slate-400">Last refreshed {widget.last_refreshed_at?new Date(widget.last_refreshed_at).toLocaleString('en-IN'):'—'}</p></div></section>
}

function WidgetBody({widget,currency}:{widget:DashboardWidgetData;currency:string}){
 if(widget.widget_type==='kpi'||widget.widget_type==='summary_card'){const data=widget.data as Record<string,unknown>|null;const value=data?.value??widget.value??0;const formatted=data?.format==='currency'?formatCurrency(Number(value),currency):new Intl.NumberFormat('en-IN').format(Number(value));return <div className="py-3"><p className="font-[Manrope] text-3xl font-bold text-slate-950">{formatted}</p><p className="mt-2 text-xs text-slate-400">{String(data?.subtitle||'ERPNext data')}</p></div>}
 if(widget.widget_type==='table'||widget.widget_type==='aging'){const data=widget.data as {columns?:Array<{key:string;label:string}>;rows?:Array<Record<string,unknown>>}|null;return <div className="overflow-x-auto"><table className="w-full min-w-[520px] text-left text-xs"><thead><tr className="border-b">{data?.columns?.map(column=><th key={column.key} className="px-3 py-2 text-[10px] uppercase text-slate-400">{column.label}</th>)}</tr></thead><tbody>{data?.rows?.map((row,index)=><tr key={String(row.name||index)} className="border-b last:border-0">{data.columns?.map(column=><td key={column.key} className="whitespace-nowrap px-3 py-2.5 text-slate-600">{String(row[column.key]??'—')}</td>)}</tr>)}</tbody></table></div>}
 const rows=Array.isArray(widget.data)?widget.data:[];if(!rows.length)return <div className="py-12 text-center text-xs text-slate-400">No permitted data available.</div>
 const config=widget.chart_config||{};const chartType=String(config.chart_type||config.chartType||widget.widget_type.replace('_chart',''));const xKey=String(config.x_key||config.xKey||config.name_key||config.nameKey||'label');const yKey=String(config.y_key||config.yKey||config.value_key||config.valueKey||'value');const seriesKey=String(((config.series as Array<Record<string,unknown>>|undefined)?.[0]?.data_key)||((config.series as Array<Record<string,unknown>>|undefined)?.[0]?.dataKey)||yKey);const axes=<><CartesianGrid stroke="#eef2f6" vertical={false}/><XAxis dataKey={xKey} axisLine={false} tickLine={false} tick={{fontSize:10,fill:'#94a3b8'}}/><YAxis axisLine={false} tickLine={false} tick={{fontSize:10,fill:'#94a3b8'}}/><Tooltip contentStyle={{borderRadius:10,fontSize:11}}/></>
 return <div className="h-64"><ResponsiveContainer width="100%" height="100%">{chartType==='line'?<LineChart data={rows}>{axes}<Line type="monotone" dataKey={seriesKey} stroke={chartPalette[0]} strokeWidth={2.5}/></LineChart>:chartType==='area'?<AreaChart data={rows}>{axes}<Area type="monotone" dataKey={seriesKey} stroke={chartPalette[4]} fill={`${chartPalette[4]}24`}/></AreaChart>:chartType==='pie'||chartType==='donut'?<PieChart><Tooltip/><Pie data={rows} dataKey={yKey} nameKey={xKey} innerRadius={chartType==='donut'?48:0} outerRadius={82}>{rows.map((_,index)=><Cell key={index} fill={chartPalette[index%chartPalette.length]}/>)}</Pie></PieChart>:<BarChart data={rows}>{axes}<Bar dataKey={seriesKey} radius={[6,6,0,0]}>{rows.map((_,index)=><Cell key={index} fill={chartPalette[index%chartPalette.length]}/>)}</Bar></BarChart>}</ResponsiveContainer></div>
}
