import { useEffect, useState } from 'react'
import { X } from 'lucide-react'
import type { DashboardWidgetData, UpdateDashboardWidgetRequest, WidgetType } from '../../types/dashboard'
const types:WidgetType[]=['kpi','line_chart','bar_chart','pie_chart','donut_chart','area_chart','table','aging','summary_card']
export function WidgetConfigDialog({widget,onClose,onSave,saving=false}:{widget:DashboardWidgetData;onClose:()=>void;onSave:(request:UpdateDashboardWidgetRequest)=>void;saving?:boolean}){
 const [title,setTitle]=useState(widget.title);const [type,setType]=useState<WidgetType>(widget.widget_type);const [interval,setInterval]=useState(widget.refresh_interval_seconds||300)
 useEffect(()=>{setTitle(widget.title);setType(widget.widget_type)},[widget])
 return <div className="fixed inset-0 z-[80] flex items-center justify-center bg-slate-950/50 p-4"><div className="w-full max-w-md rounded-2xl bg-white shadow-2xl"><header className="flex items-center justify-between border-b p-5"><div><h2 className="font-bold">Configure widget</h2><p className="mt-1 text-xs text-slate-400">Source: {widget.source.doctype||widget.source.report_name||widget.source.source_name}</p></div><button onClick={onClose} className="rounded-lg p-2 hover:bg-slate-100"><X size={17}/></button></header><div className="space-y-4 p-5"><label className="block text-xs font-bold">Title<input value={title} onChange={e=>setTitle(e.target.value)} className="mt-2 h-10 w-full rounded-xl border px-3 text-sm"/></label><label className="block text-xs font-bold">Widget type<select value={type} onChange={e=>setType(e.target.value as WidgetType)} className="mt-2 h-10 w-full rounded-xl border px-3 text-sm">{types.map(value=><option key={value} value={value}>{value.replaceAll('_',' ')}</option>)}</select></label><label className="block text-xs font-bold">Refresh interval<input type="number" min={30} value={interval} onChange={e=>setInterval(Number(e.target.value))} className="mt-2 h-10 w-full rounded-xl border px-3 text-sm"/></label></div><footer className="flex justify-end gap-2 border-t p-4"><button onClick={onClose} className="btn-secondary">Cancel</button><button disabled={saving||!title.trim()} onClick={()=>onSave({title:title.trim(),widget_type:type,refresh_interval_seconds:interval})} className="btn-primary">Save changes</button></footer></div></div>
}
