import {useEffect,useState} from 'react'
import {Mail} from 'lucide-react'
import {LoadingState} from '../../../components/common/LoadingState'
import {MailSidebar} from '../components/MailSidebar'
import {MailSearchBar} from '../components/MailSearchBar'
import {MailFilters} from '../components/MailFilters'
import {MailList} from '../components/MailList'
import {MailThreadView} from '../components/MailThreadView'
import {MailComposer} from '../components/MailComposer'
import {useCommunications} from '../hooks/useCommunications'
import {useCommunicationThread} from '../hooks/useCommunicationThread'
import type {MailFolder} from '../types/communication.types'

export function CommunicationCenterPage(){const[folder,setFolder]=useState<MailFolder>('inbox');const[search,setSearch]=useState('');const[filters,setFilters]=useState<Record<string,unknown>>({});const[selected,setSelected]=useState<string>();const[compose,setCompose]=useState(false);const[initial,setInitial]=useState<Record<string,string>>();const list=useCommunications(folder,search,filters);useEffect(()=>{if(!selected&&list.data?.items[0])setSelected(list.data.items[0].name)},[list.data,selected]);const thread=useCommunicationThread(selected);const openComposer=(value?:Record<string,string>)=>{setInitial(value);setCompose(true)};return <div className="-m-4 flex h-[calc(100vh-72px)] flex-col overflow-hidden bg-white sm:-m-6 lg:-m-8"><div className="flex items-center justify-between border-b px-4 py-3"><div className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-xl bg-indigo-50 text-indigo-600"><Mail size={18}/></span><div><h1 className="text-sm font-bold text-slate-900">Communication Center</h1><p className="text-[10px] text-slate-400">Business email powered by ERPNext Communication</p></div></div><span className="rounded-full bg-emerald-50 px-2 py-1 text-[9px] font-bold text-emerald-700">ERPNext connected</span></div><div className="flex min-h-0 flex-1 flex-col md:flex-row"><MailSidebar active={folder} onChange={value=>{setFolder(value);setSelected(undefined)}} onCompose={()=>openComposer()}/><section className={`${selected?'hidden lg:flex':'flex'} min-h-0 w-full flex-col border-r border-slate-200 md:w-[330px] lg:flex`}><div className="border-b p-3"><MailSearchBar value={search} onChange={setSearch}/><MailFilters filters={filters} onChange={setFilters}/></div>{list.isLoading?<LoadingState cards={4}/>:list.isError?<div className="p-5 text-xs text-rose-600">Unable to load communications.</div>:<MailList items={list.data?.items||[]} selected={selected} onSelect={setSelected}/>}</section><main className={`${selected?'block':'hidden lg:block'} min-w-0 flex-1 bg-white`}>{thread.isLoading?<LoadingState cards={3}/>:thread.data?<><button onClick={()=>setSelected(undefined)} className="m-3 text-xs font-bold text-indigo-600 lg:hidden">← Back to messages</button><MailThreadView thread={thread.data} onRefresh={()=>void thread.refetch()} onCompose={openComposer}/></>:<div className="grid h-full place-items-center text-center"><div><Mail size={38} className="mx-auto text-slate-200"/><p className="mt-3 text-sm font-bold text-slate-500">Select a communication</p></div></div>}</main></div><MailComposer open={compose} onClose={()=>setCompose(false)} initial={initial} onSent={()=>void list.refetch()}/></div>}
